[build]
publish = "/build"
command = "bundler exec middleman build"

[build.processing]
skip_processing = false

[build.processing.css]
minify = true
bundle = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[context.production]
publish = "/build"
command = "bundler exec middleman build"

